
### 쿠폰 정책 생성
POST http://localhost:8080/admin/coupon-policy
Content-Type: application/json

{
    "name": "5월 생일 축하 10% 할인",
    "comment": "BIRTHDAY",
    "discountType": "PERCENTAGE",
    "discountValue": 10,
    "minPayValue": 50000,
    "maxDiscountValue": 10000
}


### 쿠폰 정책 조회
GET http://localhost:8080